package scriptures

import(
    "fmt"
    "time"
    "bcolors"
    "math/rand"
)

var verses = map[int]string{
    1: `In the beginning God created the heaven and the earth    Gen.1:1`,
    2: `And God saw the light, that it was good: and God divided the light from the darkness.    Gen.1:4`,
    3: `I will bless thee...  and thou shalt be a blessing    Gen.12:2`,
    4: `I am thy shield, and thy exceeding great reward    Gen.15:1`,
    5: `Fear ye not, stand still, and see the salvation of the LORD    Ex.14:13`,
    6: `I will make all My goodness pass before thee    Ex.33:19`,
    7: `The LORD God, merciful and gracious    Ex.34:6`,
    8: `I set my tabernacle among you    Lev.26:11`,
    9: `I will walk among you, and will be your God    Lev.26:12`,
    10: `The LORD is longsuffering, and of great mercy    Num.14:18`,
    11: `Thou shalt love the LORD thy God with all thine heart    Deut.6:5`,
    12: `Shall ye lay up these my words in your heart and in your soul    Deut.11:18`,
    13: `Thou shalt rejoice before the LORD thy God    Deut.12:18`,
    14: `Blessed shalt thou be in the city, and blessed shalt thou be in the field    Deut.28:3`,
    15: `Blessed shall be the fruit of thy body, and the fruit of thy ground    Deut.28:4`,
    16: `Blessed shall be thy basket and thy store    Deut.28:5`,
    17: `Blessed shalt thou be when thou comest in, and blessed shalt thou be when thou goest out    Deut.28:6`,
    18: `They shall come out against thee one way, and flee before thee seven ways    Deut.28:7`,
    19: `And the LORD shall make thee the head, and not the tail    Deut.28:13`,
    20: `Be strong and of a good courage, fear not, nor be afraid    Deut.31:6`,
    21: `I will not fail thee, nor forsake thee    Josh.1:5`,
    22: `Only be thou strong and very courageous    Josh.1:7`,
    23: `This Book of the Law shall not depart out of thy mouth    Josh.1:8`,
    24: `Have not I commanded thee? Be strong and of a good courage    Josh.1:9`,
    25: `Be not afraid, neither be thou dismayed: for the LORD thy God is with thee    Josh.1:9`,
    26: `Sanctify yourselves: for to morrow the LORD will do wonders among you    Josh.3:5`,
    27: `The LORD your God, He it is that fighteth for you    Josh.23:10`,
    28: `Nay; but we will serve the LORD!    Josh.24:21`,
    29: `I will never break my covenant with you    Judg.2:1`,
    30: `Them that love him be as the sun when he goeth forth in his might    Judg.5:31`,
    31: `Thy people shall be my people, and thy God my God    Ruth 1:16`,
    32: `He will keep the feet of His saints    1Sam.2:9`,
    33: `Only fear the LORD, and serve Him in truth with all your heart    1Sam.12:24`,
    34: `I will shew thee what thou shalt do    1Sam.16:3`,
    35: `Man looketh on the outward appearance, but the LORD looketh on the heart    1Sam.16:7`,
    36: `Yet he hath made with me an everlasting covenant    2Sam.23:5`,
    37: `Give therefore thy servant an understanding heart    1Kin.3:9`,
    38: `The LORD your God ye shall fear; and he shall deliver you    2Kin.17:39`,
    39: `Serve Him with a perfect heart and with a willing mind    1Chr.28:9`,
    40: `The LORD searcheth all hearts, and understandeth all the imaginations of the thoughts    1Chr.28:9`,
    41: `If thou seek him, he will be found of thee    1Chr.28:9`,
    42: `The LORD is able to give thee much more than this    2Chr.25:9`,
    43: `Will not turn away His face from you, if ye return unto him    2Chr.30:9`,
    44: `He did it with all his heart, and prospered    2Chr.31:21`,
    45: `The hand of our God is upon all them for good that seek Him    Ezdra 8:22`,
    46: `The joy of the LORD is your strength    Neh.8:10`,
    47: `And who knoweth whether thou art come to the kingdom for such a time as this?    Esther.4:14`,
    48: `Till he fill thy mouth with laughing, and thy lips with rejoicing    Job 8:21`,
    49: `I know that my redeemer liveth    Job 19:25`,
    50: `Blessed is the man that walketh not in the counsel of the ungodly    Ps.1:1`,
    51: `The LORD knoweth the way of the righteous    Ps.1:6`,
    52: `Serve the LORD with fear, and rejoice with trembling    Ps.2:11`,
    53: `Blessed are all they that put their trust in Him    Ps.2:12`,
    54: `But thou, O LORD, art a shield for me, my glory    Ps.3:3`,
    55: `Lead me, O LORD, in thy righteousness    Ps.5:8`,
    56: `For thou, LORD, wilt bless the righteous    Ps.5:12`,
    57: `For the righteous God trieth the hearts    Ps.7:9`,
    58: `I will praise thee, O LORD, with my whole heart    Ps.9:1`,
    59: `For thou, LORD, hast not forsaken them that seek Thee    Ps.9:10`,
    60: `The LORD is King for ever and ever    Ps.10:16`,
    61: `LORD, thou hast heard the desire of the humble    Ps.10:17`,
    62: `The LORD is the portion of mine inheritance and of my cup    Ps.16:5`,
    63: `Hide me under the shadow of thy wings    Ps.17:8`,
    64: `I will love thee, O LORD, my strength    Ps.18:1`,
    65: `The LORD is my rock, and my fortress, and my deliverer    Ps.18:2`,
    66: `For thou wilt light my candle    Ps.18:28`,
    67: `The LORD my God will enlighten my darkness    Ps.18:28`,
    68: `It is God that girdeth me with strength    Ps.18:32`,
    69: `The LORD liveth; and blessed be my rock    Ps.18:46`,
    70: `Let the God of my salvation be exalted    Ps.18:46`,
    71: `The heavens declare the glory of God; and the firmament sheweth His handywork    Ps.19:1`,
    72: `The law of the LORD is perfect, converting the soul    Ps.19:7`,
    73: `The testimony of the LORD is sure, making wise the simple    Ps.19:7`,
    74: `The statutes of the LORD are right, rejoicing the heart    Ps.19:8`,
    75: `The commandment of the LORD is pure, enlightening the eyes    Ps.19:8`,
    76: `The fear of the LORD is clean, enduring for ever    Ps.19:9`,
    77: `The judgments of the LORD are true and righteous altogether    Ps.19:9`,
    78: `Some trust in chariots, and some in horses: but we will remember the name of the LORD our God.    Ps.20:7`,
    79: `They shall praise the LORD that seek Him    Ps.22:26`,
    80: `All the ends of the world shall remember and turn unto the LORD    Ps.22:27`,
    81: `A seed shall serve Him    Ps.22:30`,
    82: `The LORD is my shepherd; I shall not want    Ps.23:1`,
    83: `The LORD strong and mighty, the LORD mighty in battle    Ps.24:8`,
    84: `O my God, I trust in Thee: let me not be ashamed    Ps.25:2`,
    85: `Shew me thy ways, O LORD; teach me Thy paths.    Ps.25:4`,
    86: `Good and upright is the LORD: therefore will He teach sinners in the way    Ps.25:8`,
    87: `The secret of the LORD is with them that fear Him    Ps.25:14`,
    88: `Mine eyes are ever toward the LORD; for He shall pluck my feet out of the net.    Ps.25:15`,
    89: `Teach me Thy way, O LORD    Ps.27:11`,
    90: `Wait on the LORD: be of good courage, and He shall strengthen thine heart    Ps.27:14`,
    91: `The LORD is my strength and my shield    Ps.28:7`,
    92: `My heart trusted in Him, and I am helped    Ps.28:7`,
    93: `The voice of the LORD is powerful; the voice of the LORD is full of majesty    Ps.29:4`,
    94: `The LORD will give strength unto His people    Ps.29:11`,
    95: `The LORD will bless his people with peace    Ps.29:11`,
    96: `In his favour is life    Ps.30:5`,
    97: `Be of good courage, and he shall strengthen your heart    Ps.31:24`,
    98: `Blessed is he whose transgression is forgiven    Ps.32:1`,
    99: `I will instruct thee and teach thee in the way which thou shalt go    Ps.32:8`,
    100: `He that trusteth in the LORD, mercy shall compass him about    Ps.32:10`,
    101: `Be glad in the LORD, and rejoice    Ps.32:11`,
    102: `For the word of the LORD is right; and all His works are done in truth    Ps.33:4`,
    103: `The earth is full of the goodness of the LORD    Ps.33:5`,
    104: `Our soul waiteth for the LORD: He is our help and our shield.    Ps.33:20`,
    105: `They looked unto Him, and were lightened    Ps.34:5`,
    106: `O taste and see that the LORD is good    Ps.34:8`,
    107: `They that seek the LORD shall not want any good thing    Ps.34:10`,
    108: `The LORD is nigh unto them that are of a broken heart    Ps.34:18`,
    109: `And my soul shall be joyful in the LORD: it shall rejoice in His salvation.    Ps.35:9`,
    110: `Trust in the LORD, and do good    Ps.37:3`,
    111: `Dwell in the land, and verily thou shalt be fed    Ps.37:3`,
    112: `Delight thyself also in the LORD; and He shall give thee the desires of thine heart    Ps.37:4`,
    113: `Commit thy way unto the LORD; trust also in Him; and He shall bring it to pass.    Ps.37:5`,
    114: `Rest in the LORD, and wait patiently for Him    Ps.37:7`,
    115: `The meek shall inherit the earth; and shall delight themselves in the abundance of peace    Ps.37:11`,
    116: `Wait on the LORD, and keep His way    Ps.37:34`,
    117: `The salvation of the righteous is of the LORD: He is their strength in the time of trouble.    Ps.37:39`,
    118: `Lord, all my desire is before thee    Ps.38:9`,
    119: `Blessed is that man that maketh the LORD his trust    Ps.40:4`,
    120: `I delight to do Thy will, O my God    Ps.40:8`,
    121: `Be still, and know that I am God    Ps.46:10`,
    122: `O clap your hands, all ye people; shout unto God with the voice of triumph!    Ps.47:1`,
    123: `The redemption of their soul is precious    Ps.49:9`,
    124: `Our God shall come, and shall not keep silence    Ps.50:3`,
    125: `Offer unto God thanksgiving; and pay thy vows unto the Most High    Ps.50:14`,
    126: `Call upon me in the day of trouble: I will deliver thee    Ps.50:15`,
    127: `Whoso offereth praise glorifieth Me    Ps.50:23`,
    128: `The fool hath said in his heart, "There is no God"    Ps.53:1`,
    129: `Behold, God is mine helper: the Lord is with them that uphold my soul    Ps.54:4`,
    130: `Cast thy burden upon the LORD, and He shall sustain thee    Ps.55:22`,
    131: `He shall never suffer the righteous to be moved    Ps.55:22`,
    132: `Verily there is a reward for the righteous    Ps.58:11`,
    133: `God is my defence, and the God of my mercy    Ps.59:17`,
    134: `Truly my soul waiteth upon God: from Him cometh my salvation    Ps.62:1`,
    135: `God is a refuge for us    Ps.62:8`,
    136: `God hath spoken once; twice have I heard this; that power belongeth unto God.    Ps.62:11`,
    137: `The righteous shall be glad in the LORD, and shall trust in Him    Ps.64:10`,
    138: `Thy God hath commanded thy strength    Ps.68:28`,
    139: `But it is good for me to draw near to God    Ps.73:28`,
    140: `Open thy mouth wide, and I will fill it    Ps.81:10`,
    141: `The LORD God is a sun and shield    Ps.84:11`,
    142: `The LORD will give grace and glory    Ps.84:11`,
    143: `The LORD shall give that which is good; and our land shall yield her increase.    Ps.85:12`,
    144: `For thou, Lord, art good, and ready to forgive; and plenteous in mercy    Ps.86:5`,
    145: `He that dwelleth in the secret place of the Most High shall abide under the shadow of the Almighty    Ps.91:1`,
    146: `Thou shalt not be afraid for the terror by night; nor for the arrow that flieth by day    Ps.91:5`,
    147: `Lest thou dash thy foot against a stone    Ps.91:12`,
    148: `The righteous shall flourish like the palm tree    Ps.92:12`,
    149: `The LORD reigneth, He is clothed with majesty    Ps.93:1`,
    150: `The LORD knoweth the thoughts of man, that they are vanity    Ps.94:11`,
    151: `The LORD will not cast off His people    Ps.94:14`,
    152: `Give unto the LORD the glory due unto His name    Ps.96:8`,
    153: `Worship the LORD in the beauty of holiness    Ps.96:9`,
    154: `The LORD reigneth: the world also shall be established that it shall not be moved    Ps.96:10`,
    155: `Light is sown for the righteous, and gladness for the upright in heart    Ps.97:11`,
    156: `The LORD hath made known His salvation    Ps.98:2`,
    157: `Serve the LORD with gladness    Ps.100:2`,
    158: `I will set no wicked thing before mine eyes    Ps.101:3`,
    159: `They shall perish, but thou shalt endure    Ps.102:26`,
    160: `Bless the LORD, O my soul, and forget not all His benefits    Ps.103:2`,
    161: `Forget not all His benefits    Ps.103:2`,
    162: `Who forgiveth all thine iniquities; who healeth all thy diseases    Ps.103:3`,
    163: `As the heaven is high above the earth, so great is His mercy    Ps.103:11`,
    164: `As far as the east is from the west, so far hath He removed our transgressions from us    Ps.103:12`,
    165: `I will sing unto the LORD as long as I live    Ps.104:33`,
    166: `Let the heart of them rejoice that seek the LORD!    Ps.105:3`,
    167: `Seek the LORD, and His strength: seek his face evermore!    Ps.105:4`,
    168: `O give thanks unto the LORD; for He is good: for His mercy endureth for ever.    Ps.106:1`,
    169: `He sent his word, and healed them    Ps.107:20`,
    170: `Through God we shall do valiantly    Ps.108:13`,
    171: `I will greatly praise the LORD with my mouth    Ps.109:30`,
    172: `He raiseth up the poor out of the dust, and lifteth the needy out of the dunghill    Ps.113:7`,
    173: `Ye that fear the LORD, trust in the LORD: He is their help and their shield    Ps.115:11`,
    174: `He will bless them that fear the LORD    Ps.115:13`,
    175: `I will take the cup of salvation, and call upon the name of the LORD    Ps.116:13`,
    176: `His merciful kindness is great toward us    Ps.117:2`,
    177: `It is better to trust in the LORD than to put confidence in man    Ps.118:8`,
    178: `The LORD is my strength and song, and is become my salvation    Ps.118:14`,
    179: `The right hand of the LORD doeth valiantly    Ps.118:16`,
    180: `This is the day which the LORD hath made; we will rejoice and be glad in it    Ps.118:24`,
    181: `Thy word is a lamp unto my feet, and a light unto my path    Ps.119:105`,
    182: `Great peace have they which love thy law    Ps.119:165`,
    183: `My help cometh from the LORD, which made heaven and earth    Ps.121:2`,
    184: `He will not suffer thy foot to be moved    Ps.121:3`,
    185: `The LORD is thy keeper    Ps.121:5`,
    186: `I was glad when they said unto me, "Let us go into the house of the LORD"    Ps.122:1`,
    187: `Our soul is escaped as a bird out of the snare of the fowlers    Ps.124:7`,
    188: `The snare is broken, and we are escaped    Ps.124:7`,
    189: `Our help is in the name of the LORD    Ps.124:8`,
    190: `They that trust in the LORD shall be as Mount Zion    Ps.125:1`,
    191: `They that sow in tears shall reap in joy    Ps.126:5`,
    192: `Lift up your hands... and bless the LORD    Ps.134:2`,
    193: `The LORD will perfect that which concerneth me    Ps.138:8`,
    194: `The LORD upholdeth all that fall    Ps.145:14`,
    195: `The LORD is righteous in all His ways    Ps.145:17`,
    196: `The LORD is nigh unto all them that call upon Him    Ps.145:18`,
    197: `He healeth the broken in heart, and bindeth up their wounds    Ps.147:3`,
    198: `The LORD lifteth up the meek    Ps.147:6`,
    199: `Let the children of Zion be joyful in their King    Ps.149:2`,
    200: `For the LORD taketh pleasure in His people    Ps.149:4`,
    201: `Let every thing that hath breath praise the LORD    Ps.150:6`,
    202: `The fear of the LORD is the beginning of knowledge    Prov.1:7`,
    203: `My son, if sinners entice thee, consent thou not    Prov.1:10`,
    204: `I will pour out my spirit unto you, I will make known my words unto you    Prov.1:23`,
    205: `For the LORD giveth wisdom: out of His mouth cometh knowledge and understanding    Prov.2:6`,
    206: `He layeth up sound wisdom for the righteous    Prov.2:7`,
    207: `He keepeth the paths of judgment    Prov.2:8`,
    208: `Walk in the way of good men, and keep the paths of the righteous    Prov.2:20`,
    209: `He blesseth the habitation of the just    Prov.3:33`,
    210: `I give you good doctrine, forsake ye not my law    Prov.4:2`,
    211: `Get wisdom: and with all thy getting get understanding.    Prov.4:7`,
    212: `I have taught thee in the way of wisdom; I have led thee in right paths.    Prov.4:11`,
    213: `When thou goest, thy steps shall not be straitened    Prov.4:12`,
    214: `Take fast hold of instruction    Prov.4:13`,
    215: `The path of the just is as the shining light    Prov.4:18`,
    216: `Attend to my words; incline thine ear unto my sayings    Prov.4:20`,
    217: `My words... are life unto those that find them, and health to all their flesh    Prov.4:22`,
    218: `Keep thy heart with all diligence    Prov.4:23`,
    219: `Ponder the path of thy feet, and let all thy ways be established    Prov.4:26`,
    220: `Drink waters out of thine own cistern, and running waters out of thine own well    Prov.5:15`,
    221: `For the ways of man are before the eyes of the LORD    Prov.5:21`,
    222: `For the commandment is a lamp; and the law is light    Prov.6:23`,
    223: `My son, keep my words    Prov.7:1`,
    224: `Keep my commandments, and live; and my law as the apple of thine eye    Prov.7:2`,
    225: `Wisdom is better than rubies    Prov.8:11`,
    226: `Those that seek me early shall find me    Prov.8:17`,
    227: `Blessed are they that keep my ways    Prov.8:32`,
    228: `The LORD will not suffer the soul of the righteous to famish    Prov.10:3`,
    229: `The hand of the diligent maketh rich    Prov.10:4`,
    230: `The blessing of the LORD, it maketh rich, and He addeth no sorrow with it    Prov.10:22`,
    231: `The desire of the righteous shall be granted    Prov.10:24`,
    232: `The hope of the righteous shall be gladness    Prov.10:28`,
    233: `By the blessing of the upright the city is exalted    Prov.11:11`,
    234: `He that watereth shall be watered also himself    Prov.11:25`,
    235: `He that tilleth his land shall be satisfied with bread    Prov.12:11`,
    236: `He that keepeth his mouth keepeth his life    Prov.13:3`,
    237: `The light of the righteous rejoiceth    Prov.13:9`,
    238: `He that walketh with wise men shall be wise    Prov.13:20`,
    239: `The wisdom of the prudent is to understand his way    Prov.14:8`,
    240: `The tabernacle of the upright shall flourish    Prov.14:11`,
    241: `A true witness delivereth souls    Prov.14:25`,
    242: `The fear of the LORD is a fountain of life    Prov.14:27`,
    243: `A sound heart is the life of the flesh    Prov.14:30`,
    244: `A soft answer turneth away wrath    Prov.15:1`,
    245: `The eyes of the LORD are in every place    Prov.15:3`,
    246: `He that refuseth instruction despiseth his own soul    Prov.15:32`,
    247: `The fear of the LORD is the instruction of wisdom    Prov.15:33`,
    248: `Before honour is humility    Prov.15:33`,
    249: `Commit thy works unto the LORD, and thy thoughts shall be established    Prov.16:3`,
    250: `He that ruleth his spirit than he that taketh a city    Prov.16:32`,
    251: `The furnace for gold: but the LORD trieth the hearts    Prov.17:3`,
    252: `A merry heart doeth good like a medicine    Prov.17:22`,
    253: `A broken spirit drieth the bones    Prov.17:22`,
    254: `He that hath knowledge spareth his words    Prov.17:27`,
    255: `The name of the LORD is a strong tower    Prov.18:10`,
    256: `Death and life are in the power of the tongue    Prov.18:21`,
    257: `A man that hath friends must shew himself friendly    Prov.18:24`,
    258: `The discretion of a man deferreth his anger    Prov.19:11`,
    259: `He that keepeth the commandment keepeth his own soul    Prov.19:16`,
    260: `He that hath pity upon the poor lendeth unto the LORD    Prov.19:17`,
    261: `It is an honour for a man to cease from strife    Prov.20:3`,
    262: `Wait on the LORD, and he shall save thee    Prov.20:22`,
    263: `The LORD pondereth the hearts    Prov.21:2`,
    264: `A good name is rather to be chosen than great riches    Prov.22:1`,
    265: `He that hath a bountiful eye shall be blessed    Prov.22:9`,
    266: `Drowsiness shall clothe a man with rags    Prov.23:21`,
    267: `Through wisdom is an house builded; and by understanding it is established    Prov.24:3`,
    268: `By wise counsel thou shalt make thy war    Prov.24:6`,
    269: `In multitude of counsellors there is safety    Prov.24:6`,
    270: `For a just man falleth seven times, and riseth up again    Prov.24:16`,
    271: `A soft tongue breaketh the bone    Prov.25:15`,
    272: `The righteous are bold as a lion    Prov.28:1`,
    273: `When righteous men do rejoice, there is great glory    Prov.28:12`,
    274: `He that tilleth his land shall have plenty of bread    Prov.28:19`,
    275: `The righteous considereth the cause of the poor    Prov.29:7`,
    276: `Honour shall uphold the humble in spirit    Prov.29:23`,
    277: `To every thing there is a season, and a time to every purpose under the heaven    Eccl.3:1`,
    278: `A time to cast away stones, and a time to gather stones together    Eccl.3:5`,
    279: `A time to keep silence, and a time to speak    Eccl.3:7`,
    280: `Whatsoever God doeth, it shall be for ever    Eccl.3:14`,
    281: `A threefold cord is not quickly broken    Eccl.4:12`,
    282: `Keep thy foot when thou goest to the house of God, and be more ready to hear    Eccl.5:1`,
    283: `Seeing there be many things that increase vanity    Eccl.6:11`,
    284: `Anger resteth in the bosom of fools    Eccl.7:9`,
    285: `God hath made man upright; but they have sought out many inventions    Eccl.7:29`,
    286: `A man's wisdom maketh his face to shine    Eccl.8:1`,
    287: `A wise man's heart discerneth both time and judgment    Eccl.8:5`,
    288: `It shall be well with them that fear God    Eccl.8:12`,
    289: `Let thy head lack no ointment    Eccl.9:8`,
    290: `Whatsoever thy hand findeth to do, do it with thy might    Eccl.9:10`,
    291: `Wisdom is better than weapons of war    Eccl.9:18`,
    292: `He that diggeth a pit shall fall into it    Eccl.10:8`,
    293: `Whoso breaketh an hedge, a serpent shall bite him    Eccl.10:8`,
    294: `Cast thy bread upon the waters    Eccl.11:1`,
    295: `He that observeth the wind shall not sow    Eccl.11:4`,
    296: `Remember now thy Creator in the days of thy youth    Eccl.12:1`,
    297: `Vanity of vanities, saith the Preacher; all is vanity    Eccl.12:8`,
    298: `Fear God, and keep his commandments: for this is the whole duty of man    Eccl.12:13`,
    299: `Take us the foxes, the little foxes, that spoil the vines    Song 2:15`,
    300: `Many waters cannot quench love    Song 8:7`,
    301: `Learn to do well    Is.1:17`,
    302: `Though your sins be as scarlet, they shall be as white as snow    Is.1:18`,
    303: `He will teach us of his ways, and we will walk in His paths    Is.2:3`,
    304: `Whom shall I send, and who will go for Us?    Is.6:8`,
    305: `Then said I, Here am I; send me.    Is.6:8`,
    306: `The LORD JEHOVAH is my strength and my song    Is.12:2`,
    307: `In the LORD JEHOVAH is everlasting strength    Is.26:4`,
    308: `My people shall dwell in a peaceable habitation    Is.32:18`,
    309: `In the wilderness shall waters break out, and streams in the desert    Is.35:6`,
    310: `He shall feed his flock like a shepherd    Is.40:11`,
    311: `He giveth power to the faint; and to them that have no might He increaseth strength    Is.40:29`,
    312: `They that wait upon the LORD shall renew their strength    Is.40:31`,
    313: `They shall run, and not be weary; and they shall walk, and not faint    Is.40:31`,
    314: `I the LORD thy God will hold thy right hand    Is.41:13`,
    315: `Fear not; I will help thee    Is.41:13`,
    316: `I will make the wilderness a pool of water    Is.41:18`,
    317: `I will make darkness light before them    Is.42:16`,
    318: `I will even make a way in the wilderness, and rivers in the desert    Is.43:19`,
    319: `I, even I, am he that blotteth out thy transgressions     Is.43:25`,
    320: `Return unto Me; for I have redeemed thee    Is.44:22`,
    321: `The word is gone out of my mouth in righteousness, and shall not return    Is.45:23`,
    322: `I am the LORD thy God which teacheth thee to profit    Is.48:17`,
    323: `I have put my words in thy mouth    Is.51:16`,
    324: `I have covered thee in the shadow of Mine hand    Is.51:16`,
    325: `He is despised and rejected of men; a Man of sorrows, and acquainted with grief    Is.53:3`,
    326: `Surely he hath borne our griefs, and carried our sorrows    Is.53:4`,
    327: `He was wounded for our transgressions, He was bruised for our iniquities    Is.53:5`,
    328: `The chastisement of our peace was upon Him    Is.53:5`,
    329: `With his stripes we are healed    Is.53:5`,
    330: `The LORD hath laid on him the iniquity of us all    Is.53:6`,
    331: `He shall see of the travail of His soul, and shall be satisfied    Is.53:11`,
    332: `He bare the sin of many, and made intercession for the transgressors    Is.53:12`,
    333: `Enlarge the place of thy tent    Is.54:2`,
    334: `My kindness shall not depart from thee    Is.54:10`,
    335: `No weapon that is formed against thee shall prosper    Is.54:17`,
    336: `Thou shalt be like a watered garden    Is.58:11`,
    337: `The LORD shall be thine everlasting light    Is.60:20`,
    338: `I all their affliction he was afflicted    Is.63:9`,
    339: `Ask for the old paths, where is the good way, and walk therein    Jer.6:16`,
    340: `I am with thee to save thee and to deliver thee    Jer.15:20`,
    341: `I the LORD search the heart, I try the reins    Jer.17:10`,
    342: `Ye shall seek Me, and find Me, when ye shall search for Me with all your heart    Jer.29:13`,
    343: `I will forgive their iniquity, and their sin I will remember no more    Jer.31:34`,
    344: `I am the LORD, the God of all flesh: is there any thing too hard for Me?    Jer.32:27`,
    345: `I will rejoice over them to do them good    Jer.32:41`,
    346: `Call unto Me, and I will answer thee    Jer.33:3`,
    347: `I will shew thee great and mighty things, which thou knowest not    Jer.33:3`,
    348: `Obey, I beseech thee, the voice of the LORD    Jer.38:20`,
    349: `Come, and let us join ourselves to the LORD    Jer.50:5`,
    350: `The LORD is good unto them that wait for him    Lam.3:25`,
    351: `Let us search and try our ways, and turn again to the LORD    Lam.3:40`,
    352: `Let us lift up our heart with our hands unto God in the heavens    Lam.3:41`,
    353: `Cast away from you all your transgressions, whereby ye have transgressed    Ezek.18:31`,
    354: `I will accept you with your sweet savour    Ezek.20:41`,
    355: `I will cause the shower to come down in his season    Ezek.34:26`,
    356: `There shall be showers of blessing    Ezek.34:26`,
    357: `A new heart also will I give you, and a new spirit will I put within you    Ezek.36:26`,
    358: `Our God whom we serve is able to deliver us    Dan.3:17`,
    359: `For I desired mercy, and not sacrifice    Hos.6:6`,
    360: `Turn ye even to me with all your heart    Joel 2:12`,
    361: `Be glad and rejoice in the LORD your God    Joel 2:23`,
    362: `I will pour out My Spirit upon all flesh    Joel 2:28`,
    363: `Whosoever shall call on the name of the LORD shall be delivered    Joel 2:32`,
    364: `The LORD will be the hope of his people    Joel 3:16`,
    365: `Seek ye me, and ye shall live    Amos 5:4`,
    366: `The day of the LORD is near upon all the heathen    Obad.1:15`,
    367: `Salvation is of the LORD    Jon.2:9`,
    368: `We will walk in the name of the LORD our God    Mic.4:5`,
    369: `I will wait for the God of my salvation    Mic.7:7`,
    370: `The LORD knoweth them that trust in him    Nah.1:7`,
    371: `The just shall live by his faith    Hab.2:4`,
    372: `O LORD, revive thy work in the midst of the years    Hab.3:2`,
    373: `The LORD thy God in the midst of thee is mighty; He will save    Zeph.3:17`,
    374: `Thus saith the LORD of hosts; Consider your ways.    Hag.1:7`,
    375: `Be strong... for I am with you, saith the LORD    Hag.2:4`,
    376: `My spirit remaineth among you: fear ye not!    Hag.2:5`,
    377: `Fear not, but let your hands be strong    Zech.8:13`,
    378: `For I am the LORD, I change not    Mal.3:6`,
    379: `Bring ye all the tithes into the storehouse    Mal.3:10`,
    380: `And all nations shall call you blessed    Mal.3:12`,
    381: `Unto you that fear My name shall the Sun of Righteousness arise    Mal.4:2`,
    382: `Prepare ye the way of the Lord, make His paths straight    Matt.3:3`,
    383: `Therefore fruits meet for repentance    Matt.3:8`,
    384: `He shall baptize you with the Holy Ghost, and with fire    Matt.3:11`,
    385: `He will throughly purge His floor, and gather His wheat into the garner    Matt.3:12`,
    386: `Man shall not live by bread alone    Matt.4:4`,
    387: `Thou shalt worship the LORD thy God    Matt.4:10`,
    388: `Repent: for the kingdom of heaven is at hand    Matt.4:17`,
    389: `Follow Me, and I will make you fishers of men    Matt.4:19`,
    390: `Blessed are the poor in spirit: for theirs is the kingdom of heaven    Matt.5:3`,
    391: `Blessed are they that mourn: for they shall be comforted    Matt.5:4`,
    392: `Blessed are the meek: for they shall inherit the earth    Matt.5:5`,
    393: `Blessed are the merciful: for they shall obtain mercy    Matt.5:7`,
    394: `Blessed are the pure in heart: for they shall see God.    Matt.5:8`,
    395: `Blessed are the peacemakers: for they shall be called the children of God    Matt.5:9`,
    396: `Ye are the light of the world. A city that is set on an hill cannot be hid.    Matt.5:14`,
    397: `Let your light so shine before men    Matt.5:16`,
    398: `Be ye therefore perfect, even as your Father which is in heaven is perfect.    Matt.5:48`,
    399: `Your Father knoweth what things ye have need of    Matt.6:8`,
    400: `But lay up for yourselves treasures in heaven    Matt.6:20`,
    401: `For where your treasure is, there will your heart be also    Matt.6:21`,
    402: `But seek ye first the kingdom of God, and his righteousness    Matt.6:33`,
    403: `Ask, and it shall be given you    Matt.7:7`,
    404: `Seek, and ye shall find    Matt.7:7`,
    405: `Knock, and it shall be opened unto you    Matt.7:7`,
    406: `Your Father which is in heaven give good things to them that ask him    Matt.7:11`,
    407: `Narrow is the way, which leadeth unto life    Matt.7:14`,
    408: `Be of good cheer; thy sins be forgiven thee    Matt.9:2`,
    409: `Believe ye that I am able to do this?    Matt.9:28`,
    410: `The harvest truly is plenteous, but the labourers are few    Matt.9:37`,
    411: `Freely ye have received, freely give    Matt.10:8`,
    412: `Be ye therefore wise as serpents, and harmless as doves    Matt.10:16`,
    413: `What ye hear in the ear, that preach ye upon the housetops    Matt.10:27`,
    414: `Come unto Me, all ye that labour and are heavy laden, and I will give you rest    Matt.11:28`,
    415: `Learn of me; for I am meek and lowly in heart    Matt.11:29`,
    416: `My yoke is easy, and My burden is light    Matt.11:30`,
    417: `A bruised reed shall He not break    Matt.12:20`,
    418: `He that gathereth not with Me scattereth abroad    Matt.12:30`,
    419: `Then shall the righteous shine forth as the sun in the kingdom of their Father    Matt.13:43`,
    420: `The kingdom of heaven is like unto treasure hid in a field    Matt.13:44`,
    421: `I will build My church; and the gates of hell shall not prevail against it    Matt.16:18`,
    422: `Many that are first shall be last; and the last shall be first    Matt.19:30`,
    423: `He that shall endure unto the end, the same shall be saved    Matt.24:13`,
    424: `And this gospel of the kingdom shall be preached in all the world    Matt.24:14`,
    425: `Heaven and earth shall pass away, but My words shall not pass away    Matt.24:35`,
    426: `Who then is a faithful and wise servant    Matt.24:45`,
    427: `Watch and pray, that ye enter not into temptation    Matt.26:41`,
    428: `The spirit indeed is willing, but the flesh is weak    Matt.26:41`,
    429: `Go ye therefore, and teach all nations    Matt.28:19`,
    430: `And, lo, I am with you alway, even unto the end of the world    Matt.28:20`,
    431: `And in the morning, rising up a great while before day... prayed    Mark 1:35`,
    432: `And as many as touched Him were made whole    Mark 6:56`,
    433: `What would ye that I should do for you?    Mark 10:36`,
    434: `Repent ye, and believe the gospel    Mark 11:15`,
    435: `Go ye into all the world, and preach the gospel to every creature    Mark 16:15`,
    436: `Blessed are ye that weep now: for ye shall laugh    Luke 6:21`,
    437: `Take up his cross daily, and follow me    Luke 9:23`,
    438: `In the beginning was the Word, and the Word was with God, and the Word was God    John 1:1`,
    439: `And the light shineth in darkness; and the darkness comprehended it not.    John 1:5`,
    440: `But as many as received him, to them gave he power to become the sons of God    John 1:12`,
    441: `And the Word was made flesh, and dwelt among us    John 1:14`,
    442: `Make straight the way of the LORD    John 1:23`,
    443: `Hereafter ye shall see heaven open    John 1:51`,
    444: `Except a man be born again, he cannot see the kingdom of God    John 3:3`,
    445: `That which is born of the Spirit is spirit    John 3:6`,
    446: `The wind bloweth where it listeth, and thou hearest the sound thereof    John 3:8`,
    447: `For God so loved the world, that he gave his only begotten Son    John 3:16`,
    448: `He that doeth truth cometh to the light    John 3:21`,
    449: `He that believeth on the Son hath everlasting life    John 3:36`,
    450: `The true worshippers shall worship the Father in spirit and in truth    John 4:23`,
    451: `God is a Spirit: and they that worship Him must worship him in spirit and in truth    John 4:24`,
    452: `Jesus saith unto them, My meat is to do the will of Him that sent Me, and to finish His work.    John 4:34`,
    453: `He that reapeth receiveth wages, and gathereth fruit unto life eternal    John 4:36`,
    454: `He that soweth and he that reapeth may rejoice together    John 4:36`,
    455: `Behold, thou art made whole: sin no more    John 5:14`,
    456: `Search the Scriptures; for in them ye think ye have eternal life    John 5:39`,
    457: `Labour not for the meat which perisheth, but for that meat which endureth unto everlasting life    John 6:27`,
    458: `This is the work of God, that ye believe on Him whom He hath sent    John 6:29`,
    459: `For the bread of God is He which cometh down from heaven, and giveth life unto the world    John 6:33`,
    460: `He that believeth on Me shall never thirst    John 6:35`,
    461: `He that cometh to me shall never hunger    John 6:35`,
    462: `Him that cometh to Me I will in no wise cast out    John 6:37`,
    463: `He that believeth on Me hath everlasting life    John 6:47`,
    464: `It is the spirit that quickeneth; the flesh profiteth nothing    John 6:63`,
    465: `The words that I speak unto you, they are spirit, and they are life    John 6:63`,
    466: `If any man thirst, let him come unto me, and drink    John 7:37`,
    467: `He that believeth on Me... out of his belly shall flow rivers of living water    John 7:38`,
    468: `He that followeth Me shall not walk in darkness    John 8:12`,
    469: `If ye continue in My word, then are ye My disciples indeed    John 8:31`,
    470: `And ye shall know the truth, and the truth shall make you free    John 8:32`,
    471: `Whosoever committeth sin is the servant of sin    John 8:34`,
    472: `He that is of God heareth God's words    John 8:47`,
    473: `If a man keep My saying, he shall never see death    John 8:51`,
    474: `I am the door: by Me if any man enter in, he shall be saved.    John 10:9`,
    475: `I am come that they might have life, and that they might have it more abundantly    John 10:10`,
    476: `I am the good shepherd: the good shepherd giveth His life for the sheep    John 10:11`,
    477: `I am the good shepherd, and know My sheep, and am known of Mine    John 10:14`,
    478: `My sheep hear My voice, and I know them, and they follow Me.    John 10:27`,
    479: `Neither shall any man pluck them out of My hand    John 10:28`,
    480: `I am the resurrection, and the life    John 11:25`,
    481: `If thou wouldest believe, thou shouldest see the glory of God    John 11:40`,
    482: `If any man serve Me, him will My Father honour    John 12:26`,
    483: `If any man serve me, let him follow Me    John 12:26`,
    484: `While ye have light, believe in the light, that ye may be the children of light    John 12:36`,
    485: `A new commandment I give unto you, that ye love one another    John 13:34`,
    486: `By this shall all men know that ye are My disciples, if ye have love one to another    John 13:35`,
    487: `Let not your heart be troubled: ye believe in God, believe also in Me.    John 14:1`,
    488: `I will come again, and receive you unto Myself    John 14:3`,
    489: `I am the way, the truth, and the life    John 14:6`,
    490: `He that believeth on Me, the works that I do shall he do also    John 14:12`,
    491: `And whatsoever ye shall ask in My name, that will I do    John 14:13`,
    492: `If ye love Me, keep My commandments    John 14:15`,
    493: `The Comforter, which is the Holy Ghost... He shall teach you all things    John 14:26`,
    494: `Let not your heart be troubled, neither let it be afraid    John 14:27`,
    495: `Abide in Me, and I in you    John 15:4`,
    496: `He that abideth in Me, and I in him, the same bringeth forth much fruit    John 15:5`,
    497: `Herein is My Father glorified, that ye bear much fruit    John 15:8`,
    498: `I loved you: continue ye in My love    John 15:9`,
    499: `That My joy might remain in you, and that your joy might be full.    John 15:11`,
    500: `This is My commandment, that ye love one another, as I have loved you    John 15:12`,
    501: `Ye are My friends, if ye do whatsoever I command you.    John 15:14`,
    502: `Ye have not chosen Me, but I have chosen you    John 15:16`,
    503: `I have chosen you, and ordained you, that ye should go and bring forth fruit    John 15:16`,
    504: `Ask, and ye shall receive, that your joy may be full    John 16:24`,
    505: `Be of good cheer; I have overcome the world    John 16:33`,
    506: `As my Father hath sent Me, even so send I you    John 20:21`,
    507: `Blessed are they that have not seen, and yet have believed    John 20:29`,
    508: `Lord,... grant unto Thy servants, that with all boldness they may speak Thy word    Acts 4:29`,
    509: `The will of the Lord be done    Acts 21:14`,
    510: `I am not ashamed of the gospel of Christ    Rom.1:16`,
    511: `The just shall live by faith    Rom.1:17`,
    512: `The goodness of God leadeth thee to repentance    Rom.2:4`,
    513: `All have sinned, and come short of the glory of God    Rom.3:23`,
    514: `Blessed are they whose iniquities are forgiven    Rom.4:7`,
    515: `Being justified by faith, we have peace with God    Rom.5:1`,
    516: `The love of God is shed abroad in our hearts by the Holy Ghost    Rom.5:5`,
    517: `While we were yet sinners, Christ died for us    Rom.5:8`,
    518: `Being now justified by His blood, we shall be saved from wrath through Him    Rom.5:9`,
    519: `When we were enemies, we were reconciled to God by the death of His Son    Rom.5:10`,
    520: `Where sin abounded, grace did much more abound    Rom.5:20`,
    521: `Yield yourselves unto God, as those that are alive from the dead    Rom.6:13`,
    522: `The gift of God is eternal life through Jesus Christ our Lord    Rom.6:23`,
    523: `We should bring forth fruit unto God    Rom.7:4`,
    524: `We are debtors, not to the flesh, to live after the flesh    Rom.8:12`,
    525: `For as many as are led by the Spirit of God, they are the sons of God.    Rom.8:14`,
    526: `Likewise the Spirit also helpeth our infirmities.    Rom.8:26`,
    527: `All things work together for good to them that love God    Rom.8:28`,
    528: `If God be for us, who can be against us?    Rom.8:31`,
    529: `Who shall lay any thing to the charge of God's elect? It is God that justifieth.    Rom.8:33`,
    530: `Nay, in all these things we are more than conquerors through him that loved us.    Rom.8:37`,
    531: `Nor height, nor depth, nor any other creature, shall be able to separate us from the love of God    Rom.8:39`,
    532: `O man, who art thou that repliest against God?    Rom.9:20`,
    533: `Whosoever believeth on him shall not be ashamed    Rom.9:33`,
    534: `The word is nigh thee, even in thy mouth, and in thy heart    Rom.10:8`,
    535: `With the mouth confession is made unto salvation    Rom.10:10`,
    536: `The same Lord over all is rich unto all that call upon Him.    Rom.10:12`,
    537: `How beautiful are the feet of them that preach the gospel of peace    Rom.10:15`,
    538: `Faith cometh by hearing, and hearing by the word of God    Rom.10:17`,
    539: `The gifts and calling of God are without repentance    Rom.11:29`,
    540: `O the depth of the riches both of the wisdom and knowledge of God!    Rom.11:33`,
    541: `And be not conformed to this world    Rom.12:2`,
    542: `Transformed by the renewing of your mind    Rom.12:2`,
    543: `That ye may prove what is that good, and acceptable, and perfect, will of God    Rom.12:2`,
    544: `Let love be without dissimulation    Rom.12:9`,
    545: `Be kindly affectioned one to another with brotherly love    Rom.12:10`,
    546: `Fervent in spirit; serving the Lord    Rom.12:11`,
    547: `Rejoicing in hope; patient in tribulation; continuing instant in prayer    Rom.12:12`,
    548: `Rejoice with them that do rejoice, and weep with them that weep    Rom.12:15`,
    549: `Recompense to no man evil for evil    Rom.12:17`,
    550: `Live peaceably with all men    Rom.12:18`,
    551: `Be not overcome of evil, but overcome evil with good    Rom.12:21`,
    552: `Owe no man any thing, but to love one another    Rom.13:8`,
    553: `Now it is high time to awake out of sleep    Rom.13:11`,
    554: `Now is our salvation nearer than when we believed    Rom.13:11`,
    555: `Let us put on the armour of light    Rom.13:12`,
    556: `Put ye on the Lord Jesus Christ    Rom.13:14`,
    557: `So then every one of us shall give account of himself to God    Rom.14:12`,
    558: `The kingdom of God is... righteousness, and peace, and joy in the Holy Ghost.    Rom.14:17`,
    559: `Happy is he that condemneth not himself in that thing which he alloweth    Rom.14:22`,
    560: `Christ... received us to the glory of God    Rom.15:7`,
    561: `Now the God of hope fill you with all joy and peace in believing    Rom.15:13`,
    562: `The God of peace shall bruise Satan under your feet shortly    Rom.16:20`,
    563: `For the preaching of the cross is... the power of God    1Cor.1:18`,
    564: `We preach Christ crucified    1Cor.1:23`,
    565: `God hath chosen the weak things of the world to confound the things which are mighty    1Cor.1:27`,
    566: `But God hath chosen the foolish things of the world to confound the wise    1Cor.1:27`,
    567: `We have received, not the spirit of the world, but the spirit which is of God    1Cor.2:12`,
    568: `Every man shall receive his own reward according to his own labour    1Cor.3:8`,
    569: `We are labourers together with God    1Cor.3:9`,
    570: `Know ye not that ye are the temple of God?    1Cor.3:16`,
    571: `The temple of God is holy, which temple ye are    1Cor.3:17`,
    572: `Ye are Christ's; and Christ is God's    1Cor.3:23`,
    573: `We are fools for Christ's sake    1Cor.4:10`,
    574: `The kingdom of God is not in word, but in power    1Cor.4:20`,
    575: `For even Christ our passover is sacrificed for us    1Cor.5:7`,
    576: `He that is joined unto the Lord is one spirit    1Cor.6:17`,
    577: `Ye are bought with a price    1Cor.6:20`,
    578: `Glorify God in your body, and in your spirit, which are God's    1Cor.6:20`,
    579: `For the fashion of this world passeth away    1Cor.7:31`,
    580: `Knowledge puffeth up, but charity edifieth    1Cor.8:1`,
    581: `If any man love God, the same is known of Him    1Cor.8:3`,
    582: `So run, that ye may obtain    1Cor.9:24`,
    583: `Let him that thinketh he standeth take heed lest he fall    1Cor.10:12`,
    584: `God is faithful, who will not suffer you to be tempted above that ye are able    1Cor.10:13`,
    585: `Do all to the glory of God    1Cor.10:31`,
    586: `The manifestation of the Spirit is given to every man    1Cor.12:7`,
    587: `Covet earnestly the best gifts    1Cor.12:31`,
    588: `Charity suffereth long, and is kind    1Cor.13:4`,
    589: `Charity vaunteth not itself, is not puffed up    1Cor.13:4`,
    590: `Charity never faileth    1Cor.13:8`,
    591: `And now abideth faith, hope, charity, these three    1Cor.13:13`,
    592: `Follow after charity, and desire spiritual gifts    1Cor.14:1`,
    593: `Christ died for our sins according to the Scriptures    1Cor.15:3`,
    594: `But now is Christ risen from the dead    1Cor.15:20`,
    595: `Evil communications corrupt good manners    1Cor.15:33`,
    596: `Thanks be to God, which giveth us the victory    1Cor.15:57`,
    597: `Be ye stedfast, unmoveable    1Cor.15:58`,
    598: `Always abounding in the work of the Lord    1Cor.15:58`,
    599: `Your labour is not in vain in the Lord    1Cor.15:58`,
    600: `Watch ye, stand fast in the faith, quit you like men, be strong    1Cor.16:13`,
    601: `Let all your things be done with charity    1Cor.16:14`,
    602: `All the promises of God in Him are yea, and in Him Amen    2Cor.1:20`,
    603: `He which stablisheth us with you in Christ, and hath anointed us, is God    2Cor.1:21`,
    604: `Thanks be unto God, which always causeth us to triumph in Christ    2Cor.2:14`,
    605: `We are unto God a sweet savour of Christ    2Cor.2:15`,
    606: `Ye are... the epistle of Christ    2Cor.3:3`,
    607: `Our sufficiency is of God    2Cor.3:5`,
    608: `Where the Spirit of the Lord is, there is liberty    2Cor.3:17`,
    609: `God, who commanded the light to shine out of darkness, hath shined in our hearts    2Cor.4:6`,
    610: `We have this treasure in earthen vessels    2Cor.4:7`,
    611: `We are troubled on every side, yet not distressed    2Cor.4:8`,
    612: `We are perplexed, but not in despair    2Cor.4:8`,
    613: `Our light affliction... worketh for us a far more exceeding and eternal weight of glory    2Cor.4:17`,
    614: `The things which are seen are temporal; but the things which are not seen are eternal    2Cor.4:18`,
    615: `We have a building of God... in the heavens    2Cor.5:1`,
    616: `We walk by faith, not by sight    2Cor.5:7`,
    617: `If any man be in Christ, he is a new creature    2Cor.5:17`,
    618: `Old things are passed away; behold, all things are become new    2Cor.5:17`,
    619: `Be ye reconciled to God    2Cor.5:20`,
    620: `He hath made him to be sin for us, who knew no sin    2Cor.5:21`,
    621: `Behold, now is the accepted time; behold, now is the day of salvation    2Cor.6:2`,
    622: `As sorrowful, yet alway rejoicing    2Cor.6:10`,
    623: `Touch not the unclean thing; and I will receive you    2Cor.6:17`,
    624: `And will be a Father unto you, and ye shall be my sons and daughters    2Cor.6:18`,
    625: `Having therefore these promises, dearly beloved, let us cleanse ourselves    2Cor.7:1`,
    626: `For godly sorrow worketh repentance to salvation    2Cor.7:10`,
    627: `Yet for your sakes He became poor, that ye through His poverty might be rich    2Cor.8:9`,
    628: `Providing for honest things, not only in the sight of the Lord, but also in the sight of men    2Cor.8:21`,
    629: `He which soweth sparingly shall reap also sparingly    2Cor.9:6`,
    630: `God loveth a cheerful giver    2Cor.9:7`,
    631: `God is able to make all grace abound toward you    2Cor.9:8`,
    632: `That ye... may abound to every good work    2Cor.9:8`,
    633: `He that ministereth seed to the sower... multiply your seed sown    2Cor.9:10`,
    634: `Thanks be unto God for his unspeakable gift    2Cor.9:15`,
    635: `For though we walk in the flesh, we do not war after the flesh.    2Cor.10:3`,
    636: `The weapons of our warfare are not carnal    2Cor.10:4`,
    637: `Bringing into captivity every thought to the obedience of Christ    2Cor.10:5`,
    638: `But he that glorieth, let him glory in the LORD    2Cor.10:17`,
    639: `My strength is made perfect in weakness    2Cor.12:9`,
    640: `Be perfect, be of good comfort, be of one mind, live in peace.    2Cor.13:11`,
    641: `Be of one mind, live in peace    2Cor.13:11`,
    642: `Who gave Himself for our sins    Gal.1:4`,
    643: `God accepteth no man's person    Gal.2:6`,
    644: `We have believed in Jesus Christ, that we might be justified by the faith of Christ    Gal.2:16`,
    645: `Nevertheless I live; yet not I, but Christ liveth in me    Gal.2:20`,
    646: `They which are of faith, the same are the children of Abraham    Gal.3:7`,
    647: `Christ hath redeemed us from the curse of the law    Gal.3:13`,
    648: `If ye be Christ's, then are ye Abraham's seed, and heirs according to the promise    Gal.3:29`,
    649: `God hath sent forth the Spirit of his Son into your hearts    Gal.4:6`,
    650: `Wherefore thou art no more a servant, but a son; and if a son, then an heir of God    Gal.4:7`,
    651: `Stand fast therefore in the liberty wherewith Christ hath made us free    Gal.5:1`,
    652: `By love serve one another    Gal.5:13`,
    653: `Thou shalt love thy neighbour as thyself    Gal.5:14`,
    654: `Walk in the Spirit    Gal.5:16`,
    655: `The fruit of the Spirit is love, joy, peace...    Gal.5:22`,
    656: `They that are Christ's have crucified the flesh    Gal.5:24`,
    657: `If we live in the Spirit, let us also walk in the Spirit    Gal.5:25`,
    658: `Bear ye one another's burdens, and so fulfil the law of Christ.    Gal.6:2`,
    659: `Let every man prove his own work    Gal.6:4`,
    660: `Whatsoever a man soweth, that shall he also reap    Gal.6:7`,
    661: `He that soweth to the Spirit shall of the Spirit reap life everlasting    Gal.6:8`,
    662: `Let us not be weary in well doing    Gal.6:9`,
    663: `As we have therefore opportunity, let us do good unto all men    Gal.6:10`,
    664: `Blessed be the God,... who hath blessed us with every spiritual blessing    Eph.1:3`,
    665: `He hath chosen us in Him before the foundation of the world    Eph.1:4`,
    666: `In whom we have redemption through His blood, the forgiveness of sins    Eph.1:7`,
    667: `Ye were sealed with that holy Spirit of promise    Eph.1:13`,
    668: `What the riches of the glory of His inheritance in the saints    Eph.1:18`,
    669: `What is the exceeding greatness of His power to us    Eph.1:19`,
    670: `For by grace are ye saved through faith    Eph.2:8`,
    671: `For we are his workmanship, created in Christ Jesus unto good works    Eph.2:10`,
    672: `Ye who sometimes were far off are made nigh by the blood of Christ    Eph.2:13`,
    673: `Ye are... fellowcitizens with the saints, and of the household of God    Eph.2:19`,
    674: `I beseech you that ye walk worthy of the vocation wherewith ye are called    Eph.4:1`,
    675: `Unto every one of us is given grace according to the measure of the gift of Christ.    Eph.4:7`,
    676: `Speak every man truth with his neighbour    Eph.4:25`,
    677: `Grieve not the holy Spirit of God    Eph.4:30`,
    678: `Be ye kind one to another, tenderhearted    Eph.4:32`,
    679: `Forgiving one another, even as God for Christ's sake hath forgiven you    Eph.4:32`,
    680: `Be ye therefore followers of God, as dear children    Eph.5:1`,
    681: `Christ also hath loved us, and hath given Himself for us    Eph.5:2`,
    682: `Walk as children of light    Eph.5:8`,
    683: `The fruit of the Spirit is in all goodness and righteousness and truth    Eph.5:9`,
    684: `Proving what is acceptable unto the Lord    Eph.5:10`,
    685: `See then that ye walk circumspectly, not as fools, but as wise    Eph.5:15`,
    686: `Redeeming the time, because the days are evil    Eph.5:16`,
    687: `Understanding what the will of the Lord is    Eph.5:17`,
    688: `Be filled with the Spirit    Eph.5:18`,
    689: `Christ also loved the church, and gave Himself for it    Eph.5:25`,
    690: `Be strong in the Lord, and in the power of his might    Eph.6:10`,
    691: `Put on the whole armour of God    Eph.6:11`,
    692: `We wrestle not against flesh and blood    Eph.6:12`,
    693: `Stand therefore, having your loins girt about with truth    Eph.6:14`,
    694: `Praying always with all prayer and supplication in the Spirit    Eph.6:18`,
    695: `For to me to live is Christ, and to die is gain    Phil.1:21`,
    696: `Only let your conversation be as it becometh the gospel of Christ    Phil.1:27`,
    697: `Let nothing be done through strife or vainglory    Phil.2:3`,
    698: `In lowliness of mind let each esteem other better than themselves    Phil.2:3`,
    699: `Work out your own salvation with fear and trembling    Phil.2:12`,
    700: `It is God which worketh in you both to will and to do of his good pleasure    Phil.2:13`,
    701: `Do all things without murmurings and disputings    Phil.2:14`,
    702: `I count all things but loss for the excellency of the knowledge of Christ Jesus    Phil.3:8`,
    703: `Forgetting those things which are behind, and reaching forth unto those things which are before    Phil.3:13`,
    704: `Our conversation is in heaven    Phil.3:20`,
    705: `Rejoice in the Lord alway: and again I say, Rejoice!    Phil.4:4`,
    706: `Let your moderation be known unto all men    Phil.4:5`,
    707: `The Lord is at hand    Phil.4:5`,
    708: `Be careful for nothing    Phil.4:6`,
    709: `Let your requests be made known unto God    Phil.4:6`,
    710: `I am instructed both to be full and to be hungry, both to abound and to suffer need    Phil.4:12`,
    711: `I can do all things through Christ which strengtheneth me    Phil.4:13`,
    712: `God shall supply all your need    Phil.4:19`,
    713: `That ye might be filled with the knowledge of His will    Col.1:9`,
    714: `That ye might walk worthy of the Lord    Col.1:10`,
    715: `He hath delivered us from the power of darkness    Col.1:13`,
    716: `In whom we have redemption through His blood, even the forgiveness of sins    Col.1:14`,
    717: `Christ in you, the hope of glory    Col.1:27`,
    718: `As ye have therefore received Christ Jesus the Lord, so walk ye in Him    Col.2:6`,
    719: `In Him dwelleth all the fulness of the Godhead bodily    Col.2:9`,
    720: `Ye are complete in Him    Col.2:10`,
    721: `Hath he quickened together with Him, having forgiven you all trespasses    Col.2:13`,
    722: `Seek those things which are above, where Christ sitteth on the right hand of God    Col.3:1`,
    723: `Set your affection on things above, not on things on the earth    Col.3:2`,
    724: `Your life is hid with Christ in God    Col.3:3`,
    725: `And above all these things put on charity    Col.3:14`,
    726: `Charity... is the bond of perfectness    Col.3:14`,
    727: `Let the peace of God rule in your hearts    Col.3:15`,
    728: `Be ye thankful    Col.3:15`,
    729: `Let the word of Christ dwell in you richly    Col.3:16`,
    730: `Do all in the name of the Lord Jesus    Col.3:17`,
    731: `And whatsoever ye do, do it heartily, as to the Lord    Col.3:23`,
    732: `Of the Lord ye shall receive the reward of the inheritance    Col.3:24`,
    733: `Continue in prayer    Col.4:2`,
    734: `Let your speech be alway with grace, seasoned with salt    Col.4:6`,
    735: `Take heed to the ministry which thou hast received in the Lord, that thou fulfil it    Col.4:17`,
    736: `And the Lord make you to increase and abound in love one toward another    1Thess.3:12`,
    737: `For this is the will of God, even your sanctification    1Thess.4:3`,
    738: `That every one of you should know how to possess his vessel in sanctification and honour    1Thess.4:4`,
    739: `For God hath not called us unto uncleanness, but unto holiness    1Thess.4:7`,
    740: `That ye may walk honestly toward them that are without    1Thess.4:12`,
    741: `Ye are all the children of light, and the children of the day    1Thess.5:5`,
    742: `Let us not sleep, as do others; but let us watch and be sober    1Thess.5:6`,
    743: `Let us, who are of the day, be sober    1Thess.5:8`,
    744: `For God hath not appointed us to wrath, but to obtain salvation    1Thess.5:9`,
    745: `Ever follow that which is good    1Thess.5:15`,
    746: `Rejoice evermore    1Thess.5:16`,
    747: `Pray without ceasing    1Thess.5:17`,
    748: `In every thing give thanks    1Thess.5:18`,
    749: `Prove all things; hold fast that which is good    1Thess.5:21`,
    750: `The very God of peace sanctify you wholly    1Thess.5:23`,
    751: `I pray God your whole spirit and soul and body be preserved blameless    1Thess.5:23`,
    752: `God hath from the beginning chosen you to salvation    2Thess.2:13`,
    753: `The Lord is faithful, who shall stablish you, and keep you from evil    2Thess.3:3`,
    754: `If any would not work, neither should he eat    2Thess.3:10`,
    755: `The Lord of peace himself give you peace always by all means    2Thess.3:16`,
    756: `I thank Christ Jesus our Lord, who hath enabled me    1Tim.1:12`,
    757: `Christ Jesus came into the world to save sinners    1Tim.1:15`,
    758: `There is one God, and one mediator between God and men    1Tim.2:5`,
    759: `Great is the mystery of godliness: God was manifest in the flesh    1Tim.3:16`,
    760: `We trust in the living God, who is the Saviour of all men    1Tim.4:10`,
    761: `Till I come, give attendance to reading, to exhortation, to doctrine.    1Tim.4:13`,
    762: `Neglect not the gift that is in thee, which was given thee    1Tim.4:14`,
    763: `Take heed unto thyself, and unto the doctrine; continue in them.    1Tim.4:16`,
    764: `Thou shalt not muzzle the ox that treadeth out the corn    1Tim.5:18`,
    765: `The labourer is worthy of his reward    1Tim.5:18`,
    766: `Keep thyself pure    1Tim.5:22`,
    767: `Godliness with contentment is great gain    1Tim.6:6`,
    768: `Having food and raiment let us be therewith content    1Tim.6:8`,
    769: `The love of money is the root of all evil    1Tim.6:10`,
    770: `Follow after righteousness, godliness, faith, love, patience, meekness    1Tim.6:11`,
    771: `Fight the good fight of faith    1Tim.6:12`,
    772: `Lay hold on eternal life, whereunto thou art also called    1Tim.6:12`,
    773: `Keep that which is committed to thy trust    1Tim.6:20`,
    774: `I put thee in remembrance that thou stir up the gift of God, which is in thee    2Tim.1:6`,
    775: `God hath not given us the spirit of fear; but of power, and of love, and of a sound mind    2Tim.1:7`,
    776: `Be not thou therefore ashamed of the testimony of our Lord    2Tim.1:8`,
    777: `Hold fast the form of sound words    2Tim.1:13`,
    778: `That good thing which was committed unto thee keep by the Holy Ghost, who dwelleth in us.    2Tim.1:14`,
    779: `Be strong in the grace that is in Christ Jesus    2Tim.2:1`,
    780: `Thou therefore endure hardness, as a good soldier of Jesus Christ    2Tim.2:3`,
    781: `The husbandman that laboureth must be first partaker of the fruits.    2Tim.2:6`,
    782: `Remember that Jesus Christ of the seed of David was raised from the dead    2Tim.2:8`,
    783: `If we suffer, we shall also reign with Him    2Tim.2:12`,
    784: `The Lord knoweth them that are His    2Tim.2:19`,
    785: `Follow righteousness, faith, charity, peace, with them that call on the Lord    2Tim.2:22`,
    786: `The servant of the Lord must not strive; but be gentle unto all men    2Tim.2:24`,
    787: `All that will live godly in Christ Jesus shall suffer persecution    2Tim.3:12`,
    788: `Continue thou in the things which thou hast learned    2Tim.3:14`,
    789: `All Scripture is given by inspiration of God, and is profitable for doctrine    2Tim.3:16`,
    790: `That the man of God may be perfect, throughly furnished unto all good works    2Tim.3:17`,
    791: `Preach the word; be instant in season, out of season.    2Tim.4:2`,
    792: `But watch thou in all things    2Tim.4:5`,
    793: `Do the work of an evangelist, make full proof of thy ministry.    2Tim.4:5`,
    794: `In all things shewing thyself a pattern of good works    Titus 2:7`,
    795: `The grace of God that bringeth salvation hath appeared to all men    Titus 2:11`,
    796: `Not by works of righteousness which we have done, but according to His mercy He saved us    Titus 3:5`,
    797: `That the communication of thy faith may become effectual    Philem.1:6`,
    798: `Having confidence in thy obedience I wrote unto thee    Philem.1:21`,
    799: `We ought to give the more earnest heed to the things which we have heard    Heb.2:1`,
    800: `For both He that sanctifieth and they who are sanctified are all of one    Heb.2:11`,
    801: `As the children are partakers of flesh and blood, he also himself likewise took part of the same    Heb.2:14`,
    802: `He is able to succour them that are tempted    Heb.2:18`,
    803: `For every house is builded by some man; but he that built all things is God.    Heb.3:4`,
    804: `Christ as a son over His own house; whose house are we    Heb.3:6`,
    805: `Exhort one another daily    Heb.3:13`,
    806: `For we are made partakers of Christ    Heb.3:14`,
    807: `We which have believed do enter into rest    Heb.4:3`,
    808: `Let us labour therefore to enter into that rest    Heb.4:11`,
    809: `The word of God is quick, and powerful, and sharper than any twoedged sword    Heb.4:12`,
    810: `All things are naked and opened unto the eyes of Him with whom we have to do.    Heb.4:13`,
    811: `Let us hold fast our profession    Heb.4:14`,
    812: `Let us therefore come boldly unto the throne of grace    Heb.4:16`,
    813: `Yet learned He obedience by the things which He suffered    Heb.5:8`,
    814: `Leaving the principles of the doctrine of Christ, let us go on unto perfection    Heb.6:1`,
    815: `For God is not unrighteous to forget your work and labour of love    Heb.6:10`,
    816: `Surely blessing I will bless thee, and multiplying I will multiply thee    Heb.6:14`,
    817: `Jesus... is able also to save them to the uttermost that come unto God by Him    Heb.7:25`,
    818: `Jesus... ever liveth to make intercession    Heb.7:25`,
    819: `I will be to them a God, and they shall be to me a people    Heb.8:10`,
    820: `I will put my laws into their mind, and write them in their hearts    Heb.8:10`,
    821: `The blood of Christ... purge your conscience from dead works    Heb.9:14`,
    822: `We are sanctified through the offering of the body of Jesus Christ    Heb.10:10`,
    823: `Their sins and iniquities will I remember no more    Heb.10:17`,
    824: `Let us hold fast the profession of our faith without wavering    Heb.10:23`,
    825: `Let us consider one another to provoke unto love and to good works    Heb.10:24`,
    826: `Not forsaking the assembling of ourselves together    Heb.10:25`,
    827: `Cast not away therefore your confidence, which hath great recompence of reward    Heb.10:35`,
    828: `Ye have need of patience, that, after ye have done the will of God, ye might receive the promise    Heb.10:36`,
    829: `Yet a little while, and he that shall come will come, and will not tarry    Heb.10:37`,
    830: `We are... of them that believe to the saving of the soul    Heb.10:39`,
    831: `Faith is the substance of things hoped for, the evidence of things not seen.    Heb.11:1`,
    832: `But without faith it is impossible to please Him    Heb.11:6`,
    833: `He that cometh to God must believe that He is    Heb.11:6`,
    834: `God is a rewarder of them that diligently seek him    Heb.11:6`,
    835: `Strangers and pilgrims on the earth    Heb.11:13`,
    836: `Through faith subdued kingdoms, wrought righteousness, obtained promises    Heb.11:33`,
    837: `God having provided some better thing for us    Heb.11:40`,
    838: `Let us lay aside every weight, and the sin which doth so easily beset us    Heb.12:1`,
    839: `Let us run with patience the race that is set before us    Heb.12:1`,
    840: `For the joy that was set before Him endured the cross    Heb.12:2`,
    841: `Consider Him that endured such contradiction of sinners against Himself    Heb.12:3`,
    842: `Ye have not yet resisted unto blood, striving against sin    Heb.12:4`,
    843: `Nor faint when thou art rebuked of Him    Heb.12:5`,
    844: `Lift up the hands which hang down, and the feeble knees    Heb.12:12`,
    845: `Follow peace with all men, and holiness    Heb.12:14`,
    846: `Ye are come unto mount Sion, and unto the city of the living God    Heb.12:22`,
    847: `Wherefore we receiving a kingdom which cannot be moved, let us have grace    Heb.12:28`,
    848: `Let us have grace, whereby we may serve God acceptably with reverence and godly fear    Heb.12:28`,
    849: `Let brotherly love continue.    Heb.13:1`,
    850: `Be not forgetful to entertain strangers    Heb.13:2`,
    851: `Be content with such things as ye have    Heb.13:5`,
    852: `I will never leave thee, nor forsake thee    Heb.13:5`,
    853: `The LORD is my helper, and I will not fear what man shall do unto me    Heb.13:6`,
    854: `Jesus Christ the same yesterday, and to day, and for ever    Heb.13:8`,
    855: `It is a good thing that the heart be established with grace    Heb.13:9`,
    856: `Jesus, that he might sanctify the people with His own blood, suffered without the gate    Heb.13:12`,
    857: `Let us go forth therefore unto Him without the camp, bearing His reproach.    Heb.13:13`,
    858: `Here have we no continuing city, but we seek one to come    Heb.13:14`,
    859: `By Him let us offer the sacrifice of praise to God continually, that is, the fruit of our lips    Heb.13:15`,
    860: `To do good and to communicate forget not    Heb.13:16`,
    861: `Obey them that have the rule over you    Heb.13:17`,
    862: `He that wavereth is like a wave of the sea    James 1:6`,
    863: `Blessed is the man that endureth temptation    James 1:12`,
    864: `Every good gift and every perfect gift is from above    James 1:17`,
    865: `Of His own will begat he us with the word of truth    James 1:18`,
    866: `Receive with meekness the engrafted word    James 1:21`,
    867: `Be ye doers of the word    James 1:22`,
    868: `To keep himself unspotted from the world    James 1:27`,
    869: `Mercy rejoiceth against judgment.    James 2:13`,
    870: `By works was faith made perfect    James 2:22`,
    871: `Faith without works is dead    James 2:26`,
    872: `If any man offend not in word, the same is a perfect man    James 3:2`,
    873: `The spirit that dwelleth in us lusteth to envy    James 4:5`,
    874: `God resisteth the proud, but giveth grace unto the humble    James 4:6`,
    875: `Submit yourselves therefore to God. Resist the devil.    James 4:7`,
    876: `Draw nigh to God, and He will draw nigh to you.    James 4:8`,
    877: `Humble yourselves in the sight of the Lord, and He shall lift you up.    James 4:10`,
    878: `Be patient therefore, brethren, unto the coming of the Lord    James 5:7`,
    879: `Be ye also patient; stablish your hearts    James 5:8`,
    880: `The coming of the Lord draweth nigh    James 5:8`,
    881: `That the Lord is very pitiful, and of tender mercy    James 5:11`,
    882: `Is any among you afflicted? let him pray.    James 5:13`,
    883: `Is any merry? let him sing psalms.    James 5:13`,
    884: `The prayer of faith shall save the sick    James 5:15`,
    885: `Pray one for another, that ye may be healed    James 5:16`,
    886: `The effectual fervent prayer of a righteous man availeth much    James 5:16`,
    887: `Blessed be the God... which hath begotten us again unto a lively hope    1Pet.1:3`,
    888: `Be ye holy in all manner of conversation    1Pet.1:15`,
    889: `Be ye holy; for I am holy    1Pet.1:16`,
    890: `Ye were not redeemed with corruptible things, as silver and gold, from your vain conversation    1Pet.1:18`,
    891: `Love one another with a pure heart fervently    1Pet.1:22`,
    892: `The word of the Lord endureth for ever    1Pet.1:25`,
    893: `As newborn babes, desire the sincere milk of the word    1Pet.2:2`,
    894: `Ye have tasted that the Lord is gracious    1Pet.2:3`,
    895: `He that believeth on him shall not be confounded    1Pet.2:6`,
    896: `But ye are a chosen generation, a royal priesthood, an holy nation    1Pet.2:9`,
    897: `Honour all men. Love the brotherhood. Fear God. Honour the king.    1Pet.2:17`,
    898: `Who His own self bare our sins in His own body on the tree    1Pet.2:24`,
    899: `By whose stripes ye were healed    1Pet.2:24`,
    900: `Ye were as sheep going astray; but are now returned unto the Shepherd    1Pet.2:25`,
    901: `The eyes of the Lord are over the righteous    1Pet.3:12`,
    902: `If ye suffer for righteousness' sake, happy are ye    1Pet.3:14`,
    903: `Sanctify the Lord God in your hearts    1Pet.3:15`,
    904: `Christ hath once suffered for sins,... that He might bring us to God    1Pet.3:18`,
    905: `The end of all things is at hand    1Pet.4:7`,
    906: `Use hospitality one to another without grudging    1Pet.4:9`,
    907: `As every man hath received the gift, even so minister the same one to another    1Pet.4:10`,
    908: `If any man speak, let him speak as the oracles of God    1Pet.4:11`,
    909: `If any man minister, let him do it as of the ability which God giveth    1Pet.4:11`,
    910: `The spirit of glory and of God resteth upon you    1Pet.4:14`,
    911: `Ye shall receive a crown of glory that fadeth not away    1Pet.5:4`,
    912: `Humble yourselves therefore under the mighty hand of God, that He may exalt you in due time    1Pet.5:6`,
    913: `Casting all your care upon him; for he careth for you    1Pet.5:7`,
    914: `As His divine power hath given unto us all things that pertain unto life and godliness    2Pet.1:3`,
    915: `Exceeding great and precious promises    2Pet.1:4`,
    916: `Give diligence to make your calling and election sure    2Pet.1:10`,
    917: `The Lord knoweth how to deliver the godly out of temptations    2Pet.2:9`,
    918: `The Lord is not slack concerning His promise    2Pet.3:9`,
    919: `The day of the Lord will come as a thief in the night    2Pet.3:10`,
    920: `Be diligent that ye may be found of him in peace, without spot, and blameless    2Pet.3:14`,
    921: `Account that the longsuffering of our Lord is salvation    2Pet.3:15`,
    922: `Grow in grace, and in the knowledge of our Lord    2Pet.3:18`,
    923: `For the life was manifested    1John 1:2`,
    924: `Our fellowship is with the Father, and with His Son Jesus Christ    1John 1:3`,
    925: `That your joy may be full    1John 1:4`,
    926: `God is light, and in him is no darkness at all    1John 1:5`,
    927: `The blood of Jesus Christ his Son cleanseth us from all sin    1John 1:7`,
    928: `We have an advocate with the Father, Jesus Christ the righteous    1John 2:1`,
    929: `Whoso keepeth His word, in him verily is the love of God perfected    1John 2:5`,
    930: `The darkness is past, and the true light now shineth    1John 2:8`,
    931: `Your sins are forgiven you for His name's sake    1John 2:12`,
    932: `And the world passeth away, and the lust thereof    1John 2:17`,
    933: `He that doeth the will of God abideth for ever    1John 2:17`,
    934: `This is the promise that he hath promised us, even eternal life    1John 2:25`,
    935: `And now, little children, abide in Him    1John 2:28`,
    936: `Behold, what manner of love the Father hath bestowed upon us    1John 3:1`,
    937: `Beloved, now are we the sons of God    1John 3:2`,
    938: `He was manifested to take away our sins    1John 3:5`,
    939: `Hereby perceive we the love of God, because He laid down His life for us    1John 3:16`,
    940: `Let us not love in word, neither in tongue; but in deed and in truth    1John 3:18`,
    941: `If our heart condemn us not, then have we confidence toward God    1John 3:21`,
    942: `Greater is he that is in you, than he that is in the world    1John 4:4`,
    943: `Let us love one another: for love is of God    1John 4:7`,
    944: `God is love    1John 4:8`,
    945: `The love of God was manifested toward us    1John 4:9`,
    946: `He loved us, and sent his Son to be the propitiation for our sins    1John 4:10`,
    947: `if God so loved us, we ought also to love one another    1John 4:11`,
    948: `The Father sent the Son to be the Saviour of the world    1John 4:14`,
    949: `And we have known and believed the love that God hath to us    1John 4:16`,
    950: `There is no fear in love; but perfect love casteth out fear    1John 4:18`,
    951: `We love Him, because he first loved us    1John 4:19`,
    952: `His commandments are not grievous    1John 5:3`,
    953: `Whatsoever is born of God overcometh the world    1John 5:4`,
    954: `This is the victory that overcometh the world, even our faith.    1John 5:4`,
    955: `God hath given to us eternal life    1John 5:11`,
    956: `That ye may know that ye have eternal life    1John 5:13`,
    957: `He that is begotten of God keepeth himself, and that wicked one toucheth him not    1John 5:18`,
    958: `We know that we are of God, and the whole world lieth in wickedness    1John 5:19`,
    959: `The Son of God is come, and hath given us an understanding    1John 5:20`,
    960: `This is love, that we walk after His commandments    2John 1:6`,
    961: `I wish above all things that thou mayest prosper and be in health    3John 1:2`,
    962: `Keep yourselves in the love of God    Jude 1:21`,
    963: `Blessed is he that readeth, and they that hear the words of this prophecy    Rev.1:3`,
    964: `Behold, He cometh with clouds; and every eye shall see Him    Rev.1:7`,
    965: `I am Alpha and Omega, the beginning and the ending, saith the Lord    Rev.1:8`,
    966: `I know thy works, and thy labour, and thy patience    Rev.2:2`,
    967: `To him that overcometh will I give to eat of the tree of life    Rev.2:7`,
    968: `Be thou faithful unto death, and I will give thee a crown of life    Rev.2:10`,
    969: `To him that overcometh will I give to eat of the hidden manna    Rev.2:17`,
    970: `Remember therefore how thou hast received and heard, and hold fast, and repent    Rev.3:3`,
    971: `Behold, I have set before thee an open door, and no man can shut it    Rev.3:8`,
    972: `Behold, I come quickly!    Rev.3:11`,
    973: `Hold that fast which thou hast, that no man take thy crown    Rev.3:11`,
    974: `Him that overcometh will I make a pillar in the temple of My God    Rev.3:12`,
    975: `He that hath an ear, let him hear what the Spirit saith unto the churches    Rev.3:13`,
    976: `As many as I love, I rebuke and chasten    Rev.3:19`,
    977: `Behold, I stand at the door, and knock    Rev.3:20`,
    978: `If any man hear my voice, and open the door, I will come in to him    Rev.3:20`,
    979: `To him that overcometh will I grant to sit with Me in My throne    Rev.3:21`,
    980: `Holy, holy, holy, LORD God Almighty    Rev.4:8`,
    981: `Thou art worthy, O Lord, to receive glory and honour and power    Rev.4:11`,
    982: `And hast made us unto our God kings and priests    Rev.5:10`,
    983: `Worthy is the Lamb that was slain    Rev.5:12`,
    984: `Salvation to our God which sitteth upon the throne, and unto the Lamb!    Rev.7:10`,
    985: `And God shall wipe away all tears from their eyes    Rev.7:17`,
    986: `And the smoke of the incense, which came with the prayers of the saints, ascended up before God    Rev.8:4`,
    987: `They overcame him by the blood of the Lamb, and by the word of their testimony    Rev.12:11`,
    988: `Worship Him that made heaven, and earth, and the sea, and the fountains of waters    Rev.14:7`,
    989: `Great and marvellous are Thy works, Lord God Almighty!    Rev.15:3`,
    990: `Who shall not fear Thee, O Lord, and glorify Thy name?    Rev.15:4`,
    991: `Thou art righteous, O Lord, which art, and wast, and shalt be    Rev.16:5`,
    992: `Even so, Lord God Almighty, true and righteous are thy judgments    Rev.16:7`,
    993: `Blessed is he that watcheth, and keepeth his garments    Rev.16:15`,
    994: `Behold, I make all things new    Rev.21:5`,
    995: `I will give unto him that is athirst of the fountain of the water of life freely    Rev.21:6`,
    996: `He that overcometh shall inherit all things    Rev.21:7`,
    997: `Blessed is he that keepeth the sayings of the prophecy of this book    Rev.22:7`,
    998: `He that is holy, let him be holy still    Rev.22:11`,
    999: `Whosoever will, let him take the water of life freely    Rev.22:17`,
    1000: `Even so, come, Lord Jesus!    Rev.22:20`,
}

func CommandMents() {
    fmt.Printf(bcolors.GREEN + `
    ╭───────────────────────────────────────────────╮
    │ What good is it to gain the whole world       │
    │ and lose your soul? Your Creator has wonderful│
    │ plans for you! Life Tip: Defeat the Devil by  │
    │ fasting and praying.                          │
    └───────────────────────────────────────────────┘
` + bcolors.ENDC)

    fmt.Printf(bcolors.BLUE + `
    ╭───────────────────────────────────────────────╮
    │             The Ten Commandments              │
    ├───────────────────────────────────────────────┤
    │ 1. You shall have no other gods before Me     │
    │ 2. You shall make no idols                    │
    │ 3. You shall not take the name of the Lord    │
    │    your God in vain                           │
    │ 4. Keep the Sabbath day holy                  │
    │ 5. Honor your father and your mother          │
    │ 6. You shall not murder                       │
    │ 7. You shall not commit adultery              │
    │ 8. You shall not steal                        │
    │ 9. You shall not bear false witness           │
    │10. You shall not covet                        │
    ╰───────────────────────────────────────────────╯
` + bcolors.ENDC)

    fmt.Printf(bcolors.CYAN + `
    ╭───────────────────────────────────────────────╮
    │     Type 0 to Exit & Return to Main Menu      │
    ╰───────────────────────────────────────────────╯
` + bcolors.ENDC)
}

func Narration() {
    rand.Seed(time.Now().UnixNano())

    for _, verse := range verses {
        PrintVerse(verse)
    }
}

func Verse() {
    rand.Seed(time.Now().UnixNano())

    verseIndex := rand.Intn(1000) + 1
    if message, exists := verses[verseIndex]; exists {
        fmt.Println(bcolors.BLUE + `(` + bcolors.Colors() + message + bcolors.BLINK + `🕊️` + bcolors.ENDC + bcolors.BLUE + `)` + bcolors.ENDC)
    }
}

func PrintVerse(verse string) {
    for _, char := range verse {
        fmt.Print(string(char))
        time.Sleep(50 * time.Millisecond)
    }
    fmt.Println()
}

