package setups

import (
    "fmt"
    "bcolors"
    "subprocess"
)

func KaliSetups() {
    fmt.Println(bcolors.BLUE + "[" + bcolors.ENDC + "+" + bcolors.BLUE + "] " + bcolors.GREEN + "Installing Essential tools: " + bcolors.YELLOW + "nc, zsh, wget, curl, Golang" + bcolors.ENDC)
    subprocess.Popen(`apt-get update -y; apt-get install zsh git curl -y; mkdir -p /etc/apt/trusted.gpg.d/; cd /etc/apt/trusted.gpg.d/; curl -SL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor > playit.gpg;apt-get install curl wget git zip -y; curl -SL -o /etc/apt/sources.list.d/playit-cloud.list https://playit-cloud.github.io/ppa/playit-cloud.list; dpkg --add-architecture i386; apt-get update -y; apt-get install -y tor squid privoxy iptables tmux openssh-client libpcap-dev npm openssh-server ftp ncat rlwrap powershell golang-go docker.io python3 python3-pip build-essential libssl-dev libffi-dev python3-dev python3-venv python3-pycurl python3-geoip python3-whois python3-requests python3-scapy libgeoip1 libgeoip-dev privoxy dnsmasq gophish wifipumpkin3 wifite airgeddon nuclei nikto nmap smbmap dnsrecon metasploit-framework dnsrecon feroxbuster dirsearch uniscan sqlmap commix dnsenum sslscan whatweb wafw00f wordlists wapiti xsser util-linux aha set playit libssl-dev gcc hydra wine32:i386; pip3 install --upgrade setuptools; pip3 install virtualenv; python3 -m virtualenv .africs --system-site-packages`)

    fmt.Println(bcolors.BLUE + "\n[" + bcolors.ENDC + "+" + bcolors.BLUE + "] " + bcolors.GREEN + "Installing and Configuring some github third party tools" + bcolors.ENDC)
    subprocess.Popen(`cd ~/.africana/africana-base/androrat; mv /usr/bin/zipalign /usr/bin/zipalign.bak_africana; apt install ./zipalign_8.1.0.deb --allow-downgrades -y; cd ..; git clone https://github.com/ScRiPt1337/Teardroid-phprat; cd ./Teardroid-phprat; pip3 install -r requirements.txt; wget https://github.com/ScRiPt1337/Teardroidv4_api/archive/refs/heads/main.zip; unzip main.zip; rm -rf main.zip; git clone https://github.com/devanshbatham/paramspider; cd paramspider; pip3 install .; cd ..; git clone https://github.com/Ignitetch/AdvPhishing.git; cd AdvPhishing/; chmod 777 *; ./Linux-Setup.sh; cd ..; git clone https://github.com/TermuxHackz/anonphisher; cd ./anonphisher; chmod 777 *; bash anonphisher.sh;  cp -rv ./src/externals ~/.africana/; pip3 install -r ~/.africana/africana-base/requirements.txt; go install github.com/j3ssie/osmedeus@latest; go install github.com/hahwul/dalfox/v2@latest; bash <(curl -fsSL https://raw.githubusercontent.com/osmedeus/osmedeus-base/master/install.sh)`)
}

func UbuntuSetups() {
    fmt.Println(bcolors.BLUE + "\n[" + bcolors.ENDC + "+" + bcolors.BLUE + "] " + bcolors.GREEN + "Installing Essential tools: " + bcolors.YELLOW + "nc, zsh, wget, curl, Golang" + bcolors.ENDC)
    subprocess.Popen(`echo -n "deb https://http.kali.org/kali kali-rolling main non-free contrib" >> /etc/apt/sources.list.d/kali.list; apt-get update -y; apt-get install wget zip tmux zsh git curl -y; wget "https://archive.kali.org/archive-key.asc"; apt-key add ./archive-key.asc; rm -rf ./archive-key.asc; echo -n "Package: *" >> /etc/apt/preferences.d/kali.pref; echo -n "Pin: release a=kali-rolling" >> /etc/apt/preferences.d/kali.pref; echo -n "Pin-Priority: 50" >> /etc/apt/preferences.d/kali.pref; mkdir -p /etc/apt/trusted.gpg.d/; cd /etc/apt/trusted.gpg.d/; curl -SL https://playit-cloud.github.io/ppa/key.gpg | gpg --dearmor > playit.gpg; curl -SL -o /etc/apt/sources.list.d/playit-cloud.list https://playit-cloud.github.io/ppa/playit-cloud.list; dpkg --add-architecture i386; apt-get update -y; apt-get install -y tor squid privoxy iptables openssh-client openssh-server ftp ncat rlwrap powershell golang-go docker.io python3 python3-pip build-essential libpcap-dev npm libssl-dev libffi-dev python3-dev python3-venv python3-pycurl python3-geoip python3-whois python3-requests python3-scapy libgeoip1 libgeoip-dev privoxy dnsmasq gophish wifipumpkin3 wifite airgeddon nuclei nikto nmap smbmap dnsrecon metasploit-framework dnsrecon feroxbuster dirsearch uniscan sqlmap commix dnsenum sslscan whatweb wafw00f wordlists wapiti xsser set util-linux playit hydra libssl-dev aha gcc wine32:i386;  pip3 install -r requirements.txt`)

    fmt.Println(bcolors.BLUE + "\n[" + bcolors.ENDC + "+" + bcolors.BLUE + "] " + bcolors.GREEN + "Installing and Configuring some github third party tools" + bcolors.ENDC)
    subprocess.Popen(`cd ~/.africana/africana-base/androrat; mv /usr/bin/zipalign /usr/bin/zipalign.bak_africana; apt install ./zipalign_8.1.0.deb --allow-downgrades -y; cd ..; git clone https://github.com/ScRiPt1337/Teardroid-phprat; cd ./Teardroid-phprat; pip3 install -r requirements.txt; wget https://github.com/ScRiPt1337/Teardroidv4_api/archive/refs/heads/main.zip; unzip main.zip; rm -rf main.zip; git clone https://github.com/devanshbatham/paramspider; cd paramspider; pip3 install .; cd ..; git clone https://github.com/Ignitetch/AdvPhishing.git; cd AdvPhishing/; chmod 777 *; ./Linux-Setup.sh; cd ..; git clone https://github.com/TermuxHackz/anonphisher; cd ./anonphisher; chmod 777 *; bash anonphisher.sh;  cp -rv ./src/externals ~/.africana/; pip3 install -r ~/.africana/africana-base/requirements.txt; go install github.com/j3ssie/osmedeus@latest; go install github.com/hahwul/dalfox/v2@latest; bash <(curl -fsSL https://raw.githubusercontent.com/osmedeus/osmedeus-base/master/install.sh)`)
}

func UninstallSetups() {
    subprocess.Popen(`rm -rf ~/.africana/; rm -rf /usr/local/bin/africana`)
}
